In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/home/manoj/Desktop/Work/6th Sem/DSBDA/Employee_Salary_Dataset.csv")

In [10]:
df.head()

   ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

In [12]:
df.mean(numeric_only=True)

ID                  1.800000e+01
Experience_Years    9.200000e+00
Age                 3.548571e+01
Salary              2.059147e+06
dtype: float64

In [14]:
df.median(numeric_only=True)

ID                      18.0
Experience_Years         6.0
Age                     29.0
Salary              250000.0
dtype: float64

In [16]:
df.min(numeric_only=True)

ID                     1
Experience_Years       1
Age                   17
Salary              3000
dtype: int64

In [17]:
df.max(numeric_only=True)

ID                        35
Experience_Years          27
Age                       62
Salary              10000000
dtype: int64

In [18]:
df.std(numeric_only=True)

ID                  1.024695e+01
Experience_Years    7.552950e+00
Age                 1.464355e+01
Salary              3.170124e+06
dtype: float64

In [21]:
df.describe(include="all")

               ID  Experience_Years        Age  Gender        Salary
count   35.000000          35.00000  35.000000      35  3.500000e+01
unique        NaN               NaN        NaN       2           NaN
top           NaN               NaN        NaN  Female           NaN
freq          NaN               NaN        NaN      18           NaN
mean    18.000000           9.20000  35.485714     NaN  2.059147e+06
std     10.246951           7.55295  14.643552     NaN  3.170124e+06
min      1.000000           1.00000  17.000000     NaN  3.000000e+03
25%      9.500000           2.50000  22.500000     NaN  2.250000e+04
50%     18.000000           6.00000  29.000000     NaN  2.500000e+05
75%     26.500000          15.00000  53.500000     NaN  3.270000e+06
max     35.000000          27.00000  62.000000     NaN  1.000000e+07

In [23]:
print("Correlation Matrix")
df.corr(numeric_only=True)

Correlation Matrix

                        ID  Experience_Years       Age    Salary
ID                1.000000          0.291098  0.282452  0.362092
Experience_Years  0.291098          1.000000  0.973708  0.685600
Age               0.282452          0.973708  1.000000  0.668444
Salary            0.362092          0.685600  0.668444  1.000000

In [24]:
df.loc[:, 'Age'].std()

14.643551940884361

In [25]:
grouped = df.groupby('Age')['Salary'].agg(['mean', 'median', 'min', 'max', 'std'])
print(grouped)

             mean     median      min       max           std
Age
17   1.000000e+04    10000.0    10000     10000           NaN
18   3.000000e+03     3000.0     3000      3000           NaN
21   1.722000e+04     9000.0     6000     50000  1.868534e+04
22   2.250000e+04    22500.0    20000     25000  3.535534e+03
23   6.213333e+04     8900.0     7500    170000  9.341790e+04
26   1.375000e+05   137500.0    25000    250000  1.590990e+05
27   8.700000e+04    87000.0    87000     87000           NaN
28   2.500000e+05   250000.0   250000    250000           NaN
29   4.122500e+06  4122500.0  1400000   6845000  3.850196e+06
34   5.050000e+05   505000.0    80000    930000  6.010408e+05
36   1.957500e+05   195750.0    61500    330000  1.898582e+05
39   6.000050e+06  6000050.0  6000050   6000050           NaN
40   2.201000e+05   220100.0   220100    220100           NaN
49   7.600000e+06  7600000.0  7600000   7600000           NaN
53   9.300000e+06  9300000.0  9300000   9300000           NaN
54   3.636667e+06  2950000.0   650000   7900000  3.258691e+06
55   1.540000e+06  1540000.0  1540000   1540000           NaN
62   7.500500e+06  7500500.0  5001000  10000000  3.534827e+06

In [33]:
dff = pd.read_csv("/home/manoj/Desktop/Work/6th Sem/DSBDA/iris.csv")

In [34]:
dff.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [53]:
iris = dff.groupby('species')

In [54]:
iris.describe(percentiles=[.25, .5, .75])

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.107210  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [55]:
iris.mean(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [52]:
iris.median(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

In [46]:
iris.min(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [47]:
iris.max(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [48]:
iris.describe(include='all')

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.107210  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [49]:
iris.quantile(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0